### ISSUE TITLE
Notes for Jan 12 lab

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [UBC-MDS/dsci_532_group_24#1]
Dataset: Gapminder: https://www.gapminder.org/data/

Variables: child mortality rate, causes for child deaths, cause for infant deaths

Data consultants for a charity organization. It delivers vaccines and medications for children in African countries. The organization wants to identify African countries to which it should pour resources, for specific diseases. 

Division of labor: 
Mark: Section 1: Motivation and Purpose, teamwork contract (Junhoo and Eric will share their previous contracts), code of conduct
Junghoo: Section 2: Description of the data
Eric: Section 3: Research questions and usage scenarios

Next meeting: Thursday afternoon

**Comment by jkim222383** [comment]
https://github.com/UBC-MDS/dsci_532_group_24/pull/2
https://github.com/UBC-MDS/dsci_532_group_24/pull/3
https://github.com/UBC-MDS/dsci_532_group_24/pull/4
