### ISSUE TITLE
Jan 20 meeting notes

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [UBC-MDS/dsci_532_group_24#12]
Deployment: Wednesday after the lecture. 
Interaction: Finish by Wednesday. Add another tab to show metadata and additional information. 
Reflection: This should be the last part, we will finish by Friday. 
Next meeting: Thursday night.

**Comment by jkim222383** [comment]
Deployed: https://github.com/UBC-MDS/dsci_532_group_24/pull/16
Interaction: https://github.com/UBC-MDS/dsci_532_group_24/pull/11
Plots: https://github.com/UBC-MDS/dsci_532_group_24/pull/15
Reflection: https://github.com/UBC-MDS/dsci_532_group_24/pull/22
