### ISSUE TITLE
Reflection for our app

### ISSUE THREAD

**Issue by yzr1996** [UBC-MDS/dsci_532_group_24#21]
- [x]  Add tendency plots. Two line plots, one for countries over years, the other is for diseases over years(@yzr1996 ).
- [x]  Add the border on our map(@ZIBOWANGKANGYU ). 
- [x]  We need to add the function to connect the country dropdown with the map(@ZIBOWANGKANGYU ). 
- [x]  Add the ledgend on our map(@ZIBOWANGKANGYU ).
~~- [ ]  Make stacked bar charts(@jkim222383 ).~~ No longer needed as per 2nd checkbox in https://github.com/UBC-MDS/dsci_532_group_24/issues/19#issuecomment-772973691

**Comment by jkim222383** [comment]
> * [x]   Add tendency plots. Two line plots, one for countries over years, the other is for diseases over years(@yzr1996 ).
Trends tab added in #30 to show trends for countries over multiple years
> * [x]   Add the border on our map(@ZIBOWANGKANGYU ).
Addressed in https://github.com/UBC-MDS/dsci_532_group_24/pull/23
> * [x]   We need to add the function to connect the country dropdown with the map(@ZIBOWANGKANGYU ).
Addressed in https://github.com/UBC-MDS/dsci_532_group_24/pull/23
> * [x]   Add the ledgend on our map(@ZIBOWANGKANGYU ).
Addressed in https://github.com/UBC-MDS/dsci_532_group_24/pull/23
>   ~- [ ]  Make stacked bar charts(@jkim222383 ).~ No longer needed as per 2nd checkbox in [#19 (comment)](https://github.com/UBC-MDS/dsci_532_group_24/issues/19#issuecomment-772973691)
