### ISSUE TITLE
Jan 15 Meeting Notes

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [UBC-MDS/dsci_532_group_24#6]
Scatch design:
1. Control panel on the top. 
    1.1. Year: slider to select range
    1.2. Country: dropdown selector to select one or more countries 
    1.3. Causes of child mortality: checkbox or dropdown selectors
The total number of deaths should not be the default because it can be misleading. 
2. A map of Africa. 
Placed on the right side. 
The map should always show the whole African continent. The colors on the map should only change by year and type of disease. 
3. Bar chart on the left side. 
Total numbers of deaths by country (potentially by the number of new births). Sorting will be from higher to lower.

**Comment by jkim222383** [comment]
https://github.com/UBC-MDS/dsci_532_group_24/pull/11
https://github.com/UBC-MDS/dsci_532_group_24/pull/15

**Comment by jkim222383** [comment]
app sketch in https://github.com/UBC-MDS/dsci_532_group_24/pull/7, https://github.com/UBC-MDS/dsci_532_group_24/pull/8
